# Generated by Django 4.1.10 on 2023-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='start_date',
            field=models.DateField(),
        ),
    ]
