# Generated by Django 4.1.10 on 2023-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0002_alter_overview_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('class_attended', models.IntegerField(default=0)),
                ('total_classes', models.IntegerField(default=100)),
            ],
        ),
    ]
