# Generated by Django 4.1.10 on 2023-07-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
