# Generated by Django 4.1.10 on 2023-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='duration',
            field=models.CharField(default=6, max_length=300),
        ),
    ]
