# Generated by Django 4.1.10 on 2023-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0004_details_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='duration',
            field=models.CharField(default='6 months', max_length=300),
        ),
    ]
