# Generated by Django 4.1.10 on 2023-07-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=300)),
                ('trainer_name', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('url_link', models.URLField()),
            ],
        ),
    ]
