# Generated by Django 4.1.10 on 2023-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0005_alter_details_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='mod10_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod5_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod6_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod7_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod8_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='mod9_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
