# Generated by Django 4.1.10 on 2023-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0006_liveclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
