# Generated by Django 4.1.10 on 2023-07-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0006_modules_mod10_text_modules_mod5_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='offline_fees',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='online_fees',
        ),
    ]
