# Generated by Django 4.1.10 on 2023-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=300)),
                ('location', models.CharField(default='eranakulam', max_length=200)),
                ('salary', models.PositiveIntegerField()),
                ('bond', models.PositiveIntegerField()),
                ('url_link', models.URLField()),
            ],
        ),
    ]
