# Generated by Django 4.1.10 on 2023-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarapi', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=300),
        ),
    ]
